import { ApolloClient, InMemoryCache, HttpLink, ApolloLink, from  } from '@apollo/client'
import Head from 'next/head'
import Link from 'next/link';
import { GET_ALL_POSTS } from '../graphql/queries';
import { onError } from '@apollo/client/link/error';

export default function Home({ posts }) {
  console.log("-------------------posts = ", posts);
  return (
    <div>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis neque placerat ac. </p>
      <br />
      <h2>All posts</h2>
      <br />
      {posts.map((val, i) => {
        return (
          <Link key={i} href={val.attributes.urlSlug} legacyBehavior>
            <a>
              <div className="card">
                <h3>{val.attributes.title}</h3>
                <p>{val.attributes.description}</p>
              </div>
            </a>
          </Link>
        )
      })}
    </div>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({
    uri: "http://127.0.0.1:1337/graphql",
    cache: new InMemoryCache()
  });


  // const errorLink = onError(({ graphQLErrors, networkError }) => {
  //   if (graphQLErrors)
  //     graphQLErrors.forEach(({ message, locations, path }) =>
  //       console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`),
  //     );
  //   if (networkError) console.log(`[Network error]: ${networkError}`);
  // });
  
  // const httpLink = new HttpLink({ uri: 'http://localhost:1337/graphql' });
  
  // const client = new ApolloClient({
  //   cache: new InMemoryCache(),
  //   link: from([errorLink, httpLink]),
  // });



  const { data } = await client.query({
    query: GET_ALL_POSTS
  })

  console.log("---------  -data : ", JSON.stringify(data));

  return {
    props: {
      posts: data.blogPosts.data
    }
  }
}